# 📌 Etapa 1 - Carregamento do Dataset

## Objetivo

Nesta etapa será realizado o carregamento do dataset **StackExchange StackOverflow**, disponibilizado na plataforma Hugging Face.

Esse dataset foi escolhido por reunir conteúdos técnicos em grande quantidade, sendo adequado para a preparação da base de treinamento do projeto **SCRIPTO**.

O carregamento será feito diretamente no Google Colab por meio da biblioteca `datasets`.

In [2]:
!pip install -q datasets

from datasets import load_dataset

dataset = load_dataset("mlfoundations-dev/stackexchange_stackoverflow")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/436 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  184MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/50000 [00:00<?, ? examples/s]

# 📌 Etapa 2 - Exploração Inicial do Dataset

## Objetivo

Após o carregamento do dataset, é importante conhecer sua estrutura antes de iniciar qualquer etapa de limpeza ou transformação.

Nesta fase serão verificadas:

- quantidade de registros;
- quantidade de colunas;
- nomes das colunas;
- tipo dos dados;
- estrutura geral do conjunto de dados.

Essa análise inicial permite compreender como os dados estão organizados e quais informações poderão ser utilizadas no treinamento do modelo de Inteligência Artificial do projeto SCRIPTO.

In [3]:
# Visualizando a estrutura do dataset

print(dataset)

DatasetDict({
    train: Dataset({
        features: ['instruction', 'completion', 'conversations'],
        num_rows: 50000
    })
})

# 📌 Etapa 3 - Visualização dos Primeiros Registros

## Objetivo

Após confirmar que o dataset foi carregado corretamente, é importante visualizar alguns exemplos reais antes de iniciar qualquer processamento.

Nesta etapa serão exibidos os primeiros registros do conjunto de dados para compreender:

- como as perguntas estão estruturadas;
- como as respostas são armazenadas;
- como a conversa completa é organizada.

Essa inspeção inicial facilita o entendimento do formato dos dados e auxilia nas próximas etapas de preparação para o treinamento do modelo.

In [4]:
# Convertendo a partição de treinamento para DataFrame

import pandas as pd

df = dataset["train"].to_pandas()

# Exibindo os cinco primeiros registros

df.head()

,instruction,completion,conversations
0,Question as stated in the title.\n,"It seems like you mentioned a ""title,"" but I d...","[{'from': 'human', 'value': 'Question as state..."
1,"Can it be done and if so, how? \n","Sure! I can help you with that. However, I nee...","[{'from': 'human', 'value': 'Can it be done an..."
2,I'd like a concise introduction to the differe...,"Certainly! However, I need a bit more context ...","[{'from': 'human', 'value': 'I'd like a concis..."
3,If I've got a table containing Field1 and Fiel...,"Yes, you can generate a new field in your SQL ...","[{'from': 'human', 'value': 'If I've got a tab..."
4,Here's a basic regex technique that I've never...,To match files that end with either `.sty` or ...,"[{'from': 'human', 'value': 'Here's a basic re..."

# 📌 Etapa 4 - Análise das Informações do Dataset

## Objetivo

Antes de realizar qualquer transformação é necessário identificar as características do conjunto de dados.

Nesta etapa serão analisados:

- quantidade de linhas;
- quantidade de colunas;
- nomes das colunas;
- tipos dos dados;
- existência de valores nulos.

Essas informações serão utilizadas para definir a estratégia de preparação do dataset para o projeto SCRIPTO.

In [5]:
# Informações gerais do DataFrame

print("Quantidade de linhas:", df.shape[0])
print("Quantidade de colunas:", df.shape[1])

print("\nNomes das colunas:")
print(df.columns.tolist())

print("\nTipos dos dados:")
print(df.dtypes)

print("\nValores nulos:")
print(df.isnull().sum())

Quantidade de linhas: 50000
Quantidade de colunas: 3

Nomes das colunas:
['instruction', 'completion', 'conversations']

Tipos dos dados:
instruction      object
completion       object
conversations    object
dtype: object

Valores nulos:
instruction      0
completion       0
conversations    0
dtype: int64

# 📌 Etapa 5 - Inspeção de um Registro

## Objetivo

Embora já sejam conhecidas as colunas do dataset, ainda é necessário compreender como as informações são armazenadas em cada registro.

Nesta etapa será exibido um único exemplo completo para identificar:

- formato da pergunta;
- formato da resposta;
- estrutura da conversa completa.

Essa análise permitirá definir como cada informação será extraída durante a etapa de preparação do novo dataset.

In [6]:
# Exibindo o primeiro registro completo

registro = df.iloc[0]

print("="*80)
print("INSTRUCTION")
print("="*80)
print(registro["instruction"])

print("\n")
print("="*80)
print("COMPLETION")
print("="*80)
print(registro["completion"])

print("\n")
print("="*80)
print("CONVERSATIONS")
print("="*80)
print(registro["conversations"])

================================================================================
INSTRUCTION
================================================================================
Question as stated in the title.



================================================================================
COMPLETION
================================================================================
It seems like you mentioned a "title," but I don't have access to any specific titles or context you might be referring to. Could you please provide more details or clarify your question? I'm here to help!


================================================================================
CONVERSATIONS
================================================================================
[{'from': 'human', 'value': 'Question as stated in the title.\n'}
 {'from': 'gpt', 'value': 'It seems like you mentioned a "title," but I don\'t have access to any specific titles or context you might be referring to. Could you please provide more details or clarify your question? I\'m here to help!'}]

# 📌 Etapa 6 - Estatísticas do Dataset

## Objetivo

Antes de iniciar a preparação do novo dataset, é importante obter algumas estatísticas gerais sobre os dados disponíveis.

Nesta etapa serão analisados:

- quantidade total de registros;
- tamanho médio das perguntas;
- tamanho médio das respostas;
- maior pergunta;
- maior resposta.

Essas informações auxiliam na compreensão da qualidade do conjunto de dados e ajudam na definição das próximas etapas de preparação.

In [7]:
# =====================================================
# Estatísticas gerais do dataset
# =====================================================

# Calculando o tamanho dos textos
df["tam_instruction"] = df["instruction"].str.len()
df["tam_completion"] = df["completion"].str.len()

print("="*60)
print("ESTATÍSTICAS DO DATASET")
print("="*60)

print(f"\nQuantidade de registros : {len(df):,}")
print(f"Quantidade de colunas   : {df.shape[1]}")

print("\nComprimento médio das perguntas:")
print(round(df["tam_instruction"].mean(),2), "caracteres")

print("\nComprimento médio das respostas:")
print(round(df["tam_completion"].mean(),2), "caracteres")

print("\nMaior pergunta:")
print(df["tam_instruction"].max(), "caracteres")

print("\nMaior resposta:")
print(df["tam_completion"].max(), "caracteres")

============================================================
ESTATÍSTICAS DO DATASET
============================================================

Quantidade de registros : 50,000
Quantidade de colunas   : 5

Comprimento médio das perguntas:
678.37 caracteres

Comprimento médio das respostas:
2778.67 caracteres

Maior pergunta:
27637 caracteres

Maior resposta:
49571 caracteres

# 📌 Conclusão da Exploração Inicial

A exploração inicial permitiu compreender a estrutura do conjunto de dados e confirmar sua adequação para o treinamento do modelo do projeto SCRIPTO.

Principais observações:

- O dataset possui 50.000 registros.
- Não foram encontrados valores ausentes.
- O conjunto contém três campos principais:
  - instruction (pergunta);
  - completion (resposta);
  - conversations (histórico da conversa).
- Os textos possuem tamanho suficiente para treinamento de modelos de Inteligência Artificial.
- Existe boa diversidade no tamanho das perguntas e respostas.

Com essa análise concluída, a próxima etapa será preparar os dados para atender ao formato definido pelo projeto, preservando as informações relevantes e organizando os campos necessários para o treinamento do modelo.

# 📌 Etapa 8 - Construção do Dataset do Projeto

## Objetivo

Nesta etapa será iniciado o processo de transformação do dataset original do StackExchange StackOverflow para o formato adotado pelo projeto SCRIPTO.

Como o dataset original possui apenas três campos principais (`instruction`, `completion` e `conversations`), serão criadas novas colunas para atender ao padrão definido pela equipe de desenvolvimento.

Nesta primeira transformação serão gerados os campos básicos de identificação e organização dos registros, mantendo todas as informações originais do dataset.

Essa etapa constitui a base para as próximas fases de enriquecimento e classificação automática dos conteúdos.

In [8]:
# ==========================================================
# Construindo o novo DataFrame no padrão do projeto
# ==========================================================

import pandas as pd
import numpy as np

novo_df = pd.DataFrame()

# Identificador único do registro
novo_df["record_id"] = range(1, len(df) + 1)

# Identificador da fonte
novo_df["source_id"] = [
    f"SRC-{str(i).zfill(5)}"
    for i in range(1, len(df) + 1)
]

# Origem do conteúdo
novo_df["source_type"] = "stackoverflow"

# Mantendo os campos originais
novo_df["title"] = df["instruction"]
novo_df["content"] = df["completion"]

In [9]:
# Visualizando a estrutura inicial

novo_df.head()

,record_id,source_id,source_type,title,content
0,1,SRC-00001,stackoverflow,Question as stated in the title.\n,"It seems like you mentioned a ""title,"" but I d..."
1,2,SRC-00002,stackoverflow,"Can it be done and if so, how? \n","Sure! I can help you with that. However, I nee..."
2,3,SRC-00003,stackoverflow,I'd like a concise introduction to the differe...,"Certainly! However, I need a bit more context ..."
3,4,SRC-00004,stackoverflow,If I've got a table containing Field1 and Fiel...,"Yes, you can generate a new field in your SQL ..."
4,5,SRC-00005,stackoverflow,Here's a basic regex technique that I've never...,To match files that end with either `.sty` or ...

# 📌 Etapa 9 - Inclusão dos Metadados

## Objetivo

Nesta etapa serão adicionados metadados básicos ao conjunto de dados.

In [10]:
# ==========================================================
# Adicionando metadados básicos
# ==========================================================

import numpy as np

# Autor
novo_df["author"] = "Desconhecido"

# Identificador do autor
novo_df["author_id"] = [
    f"AUT-{str(i).zfill(4)}"
    for i in range(1, len(novo_df)+1)
]

# Categoria inicial
novo_df["category"] = "Tecnologia"

# Data fictícia (será melhorada posteriormente)
novo_df["created_at"] = "2025-01-01"

In [11]:
novo_df.head()

,record_id,source_id,source_type,title,content,author,author_id,category,created_at
0,1,SRC-00001,stackoverflow,Question as stated in the title.\n,"It seems like you mentioned a ""title,"" but I d...",Desconhecido,AUT-0001,Tecnologia,2025-01-01
1,2,SRC-00002,stackoverflow,"Can it be done and if so, how? \n","Sure! I can help you with that. However, I nee...",Desconhecido,AUT-0002,Tecnologia,2025-01-01
2,3,SRC-00003,stackoverflow,I'd like a concise introduction to the differe...,"Certainly! However, I need a bit more context ...",Desconhecido,AUT-0003,Tecnologia,2025-01-01
3,4,SRC-00004,stackoverflow,If I've got a table containing Field1 and Fiel...,"Yes, you can generate a new field in your SQL ...",Desconhecido,AUT-0004,Tecnologia,2025-01-01
4,5,SRC-00005,stackoverflow,Here's a basic regex technique that I've never...,To match files that end with either `.sty` or ...,Desconhecido,AUT-0005,Tecnologia,2025-01-01

# 📌 Etapa 10 - Enriquecimento dos Metadados

## Objetivo

Nesta etapa serão gerados metadados sintéticos para tornar o conjunto de dados mais próximo de uma base real.

Serão criadas datas distribuídas ao longo do tempo, autores fictícios e categorias relacionadas ao conteúdo técnico.

Essas informações enriquecem o dataset e permitem simular um ambiente mais próximo daquele encontrado em aplicações reais de gerenciamento de conhecimento.

In [12]:
# ==========================================================
# Enriquecendo os metadados
# ==========================================================

import random

# Datas aleatórias entre 2022 e 2025
datas = pd.date_range("2022-01-01", "2025-01-01")

novo_df["created_at"] = np.random.choice(datas, size=len(novo_df))

# Lista de autores fictícios
autores = [
    "Marina Almeida",
    "Carlos Mendes",
    "Daniel Rocha",
    "Ana Souza",
    "Bruno Lima",
    "Fernanda Costa",
    "Lucas Oliveira",
    "Juliana Martins",
    "Gabriel Silva",
    "Patrícia Ramos"
]

novo_df["author"] = np.random.choice(autores, size=len(novo_df))

In [13]:
novo_df.head()

,record_id,source_id,source_type,title,content,author,author_id,category,created_at
0,1,SRC-00001,stackoverflow,Question as stated in the title.\n,"It seems like you mentioned a ""title,"" but I d...",Ana Souza,AUT-0001,Tecnologia,2022-05-12
1,2,SRC-00002,stackoverflow,"Can it be done and if so, how? \n","Sure! I can help you with that. However, I nee...",Juliana Martins,AUT-0002,Tecnologia,2024-09-06
2,3,SRC-00003,stackoverflow,I'd like a concise introduction to the differe...,"Certainly! However, I need a bit more context ...",Bruno Lima,AUT-0003,Tecnologia,2023-09-24
3,4,SRC-00004,stackoverflow,If I've got a table containing Field1 and Fiel...,"Yes, you can generate a new field in your SQL ...",Daniel Rocha,AUT-0004,Tecnologia,2024-03-05
4,5,SRC-00005,stackoverflow,Here's a basic regex technique that I've never...,To match files that end with either `.sty` or ...,Lucas Oliveira,AUT-0005,Tecnologia,2023-06-19

# 📌 Etapa 11 - Validação da Estrutura Final

## Objetivo

Após a criação dos metadados sintéticos, é importante verificar se o conjunto de dados está seguindo a estrutura esperada pelo projeto.

Nesta etapa serão conferidos:

- quantidade de registros;
- quantidade de colunas;
- nomes das colunas;
- tipos de dados;
- visualização dos primeiros registros.

Essa validação garante que o dataset esteja consistente antes das etapas de limpeza e exportação.

In [14]:
# ==========================================================
# Validação da estrutura final do dataset
# ==========================================================

print("="*70)
print("ESTRUTURA FINAL")
print("="*70)

print(f"Quantidade de registros : {len(novo_df):,}")
print(f"Quantidade de colunas   : {novo_df.shape[1]}")

print("\nColunas do dataset:\n")
print(novo_df.columns.tolist())

print("\nTipos dos dados:\n")
print(novo_df.dtypes)

======================================================================
ESTRUTURA FINAL
======================================================================
Quantidade de registros : 50,000
Quantidade de colunas   : 9

Colunas do dataset:

['record_id', 'source_id', 'source_type', 'title', 'content', 'author', 'author_id', 'category', 'created_at']

Tipos dos dados:

record_id               int64
source_id              object
source_type            object
title                  object
content                object
author                 object
author_id              object
category               object
created_at     datetime64[ns]
dtype: object

In [15]:
novo_df.head()

,record_id,source_id,source_type,title,content,author,author_id,category,created_at
0,1,SRC-00001,stackoverflow,Question as stated in the title.\n,"It seems like you mentioned a ""title,"" but I d...",Ana Souza,AUT-0001,Tecnologia,2022-05-12
1,2,SRC-00002,stackoverflow,"Can it be done and if so, how? \n","Sure! I can help you with that. However, I nee...",Juliana Martins,AUT-0002,Tecnologia,2024-09-06
2,3,SRC-00003,stackoverflow,I'd like a concise introduction to the differe...,"Certainly! However, I need a bit more context ...",Bruno Lima,AUT-0003,Tecnologia,2023-09-24
3,4,SRC-00004,stackoverflow,If I've got a table containing Field1 and Fiel...,"Yes, you can generate a new field in your SQL ...",Daniel Rocha,AUT-0004,Tecnologia,2024-03-05
4,5,SRC-00005,stackoverflow,Here's a basic regex technique that I've never...,To match files that end with either `.sty` or ...,Lucas Oliveira,AUT-0005,Tecnologia,2023-06-19

# 📌 Etapa 12 - Organização Final das Colunas

## Objetivo

Nesta etapa é realizada a organização da ordem das colunas do dataset, seguindo o padrão definido pela equipe do projeto.

Essa padronização facilita a integração do conjunto de dados com as próximas etapas de treinamento do modelo de Inteligência Artificial.

In [16]:
# ==========================================================
# Organizando as colunas conforme padrão do projeto
# ==========================================================

novo_df = novo_df[
    [
        "record_id",
        "source_id",
        "source_type",
        "author_id",
        "author",
        "created_at",
        "title",
        "content",
        "category"
    ]
]

novo_df.head()

,record_id,source_id,source_type,author_id,author,created_at,title,content,category
0,1,SRC-00001,stackoverflow,AUT-0001,Ana Souza,2022-05-12,Question as stated in the title.\n,"It seems like you mentioned a ""title,"" but I d...",Tecnologia
1,2,SRC-00002,stackoverflow,AUT-0002,Juliana Martins,2024-09-06,"Can it be done and if so, how? \n","Sure! I can help you with that. However, I nee...",Tecnologia
2,3,SRC-00003,stackoverflow,AUT-0003,Bruno Lima,2023-09-24,I'd like a concise introduction to the differe...,"Certainly! However, I need a bit more context ...",Tecnologia
3,4,SRC-00004,stackoverflow,AUT-0004,Daniel Rocha,2024-03-05,If I've got a table containing Field1 and Fiel...,"Yes, you can generate a new field in your SQL ...",Tecnologia
4,5,SRC-00005,stackoverflow,AUT-0005,Lucas Oliveira,2023-06-19,Here's a basic regex technique that I've never...,To match files that end with either `.sty` or ...,Tecnologia

In [17]:
novo_df.to_csv(
    "base_de_dados_artigos.csv",
    index=False,
    encoding="utf-8"
)

print("✅ Dataset exportado com sucesso!")

✅ Dataset exportado com sucesso!

# 📌 Etapa Final - Validação do Dataset Exportado

## Objetivo

Antes da exportação definitiva, é realizada uma validação da estrutura do dataset para garantir que todas as colunas obrigatórias estejam presentes e organizadas conforme o padrão definido pelo projeto.

Essa conferência reduz a possibilidade de erros durante a integração com as próximas etapas do pipeline de treinamento do modelo de Inteligência Artificial.

In [18]:
print("="*70)
print("VALIDAÇÃO FINAL")
print("="*70)

print("\nColunas:")
print(novo_df.columns.tolist())

print("\nQuantidade de registros:", len(novo_df))

print("\nQuantidade de colunas:", novo_df.shape[1])

print("\nValores nulos:")
print(novo_df.isnull().sum())

======================================================================
VALIDAÇÃO FINAL
======================================================================

Colunas:
['record_id', 'source_id', 'source_type', 'author_id', 'author', 'created_at', 'title', 'content', 'category']

Quantidade de registros: 50000

Quantidade de colunas: 9

Valores nulos:
record_id      0
source_id      0
source_type    0
author_id      0
author         0
created_at     0
title          0
content        0
category       0
dtype: int64

In [19]:
novo_df.to_csv(
    "base_de_dados_artigos.csv",
    index=False,
    encoding="utf-8"
)

In [20]:
from google.colab import files

files.download("base_de_dados_artigos.csv")

In [21]:
novo_df.to_csv(
    "base_de_dados_artigos.csv",
    index=False,
    encoding="utf-8"
)